### ISSUE TITLE
AssertionError while using Brisque

### ISSUE THREAD

**Issue by vss96** [ocampor/image-quality#23]
**Describe the bug**
I was trying to run Brisque on images and ended up getting an assertion error.

**Traceback**
```
Traceback (most recent call last):
  File "predict.py", line 175, in <module>
    _main_(args)
  File "predict.py", line 114, in _main_
    clarity_score = calculate_average_clarity(images[j], batch_boxes[j], pred_labels, obj_thresh)
  File "/home/ubuntu/wink/src/keras-yolo3/utils/clarity.py", line 15, in calculate_average_clarity
    clarity_score = calculate_image_clarity(image, box)
  File "/home/ubuntu/wink/src/keras-yolo3/utils/clarity.py", line 6, in calculate_image_clarity
    return 100 - brisque.score(target_object)
  File "/home/ubuntu/wink/wink7/lib/python3.7/site-packages/imquality/brisque.py", line 142, in score
    scaled_features = calculate_features(image, kernel_size, sigma)
  File "/home/ubuntu/wink/wink7/lib/python3.7/site-packages/imquality/brisque.py", line 129, in calculate_features
    features = numpy.concatenate([brisque.features, downscaled_brisque.features])
  File "/home/ubuntu/wink/wink7/lib/python3.7/site-packages/imquality/brisque.py", line 88, in features
    return numpy.concatenate([self.calculate_features(mscn_type) for mscn_type in MscnType])
  File "/home/ubuntu/wink/wink7/lib/python3.7/site-packages/imquality/brisque.py", line 88, in <listcomp>
    return numpy.concatenate([self.calculate_features(mscn_type) for mscn_type in MscnType])
  File "/home/ubuntu/wink/wink7/lib/python3.7/site-packages/imquality/brisque.py", line 101, in calculate_features
    agg = AsymmetricGeneralizedGaussian(self.get_coefficients(mscn_type)).fit()
  File "/home/ubuntu/wink/wink7/lib/python3.7/site-packages/imquality/statistics.py", line 107, in fit
    self._alpha = self.estimate_alpha(x0)
  File "/home/ubuntu/wink/wink7/lib/python3.7/site-packages/imquality/statistics.py", line 101, in estimate_alpha
    assert solution.success
AssertionError
Segmentation fault (core dumped)

```
**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version  1.2.4
 - Python 3.7

**Comment by vss96** [comment]
@ocampor Is there some package or dependency that I have missed because of which the behavior is different.

**Comment by ocampor** [comment]
No, basically the solver didn’t find a solution for that specific image. A quick solution would be to modify the tolerance of the solver, a little bit more elaborate solution would be to change the solver completely.

**Comment by ocampor** [comment]
Closing because of lack of activity.
