### ISSUE TITLE
ValueError: convolve2d inputs must both be 2-D arrays

### ISSUE THREAD

**Issue by srikarad07** [ocampor/image-quality#48]
**Describe the bug**
I just installed the tool from github (since the pypi version had some issue) and I see the following error: 

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    print(brisque.score(img))
  File "image-quality/imquality/brisque.py", line 163, in score
    scaled_features = calculate_features(image, kernel_size, sigma)
  File "image-quality/imquality/brisque.py", line 148, in calculate_features
    features = numpy.concatenate([brisque.features, downscaled_brisque.features])
  File "image-quality/imquality/brisque.py", line 95, in features
    [self.calculate_features(mscn_type) for mscn_type in MscnType]
  File "image-quality/imquality/brisque.py", line 95, in <listcomp>
    [self.calculate_features(mscn_type) for mscn_type in MscnType]
  File "image-quality/imquality/brisque.py", line 109, in calculate_features
    agg = AsymmetricGeneralizedGaussian(self.get_coefficients(mscn_type)).fit()
  File "image-quality/imquality/brisque.py", line 100, in get_coefficients
    MscnType.mscn: self.mscn,
  File "image-quality/imquality/brisque.py", line 73, in mscn
    self._mscn = (self.image - self.local_mean) / (self.local_deviation + c)
  File "image-quality/imquality/brisque.py", line 56, in local_mean
    self._local_mean = scipy.signal.convolve2d(self.image, self.kernel, "same")
  File "image-quality/env/lib/python3.8/site-packages/scipy/signal/_signaltools.py", line 1715, in convolve2d
    raise ValueError('convolve2d inputs must both be 2-D arrays')
ValueError: convolve2d inputs must both be 2-D arrays

```

**To Reproduce**
1. install the tool from github
2. run `python setup.py install `
3. create a main.py file with the example code as shown in the readme of the repo
4. take a screenshot of the github issue and use that as an example image for the test
5. run python main.py

**Expected behavior**
Expected to see the brisque score as shown in the readme

**Desktop (please complete the following information):**
 - OS: MacOS ventura 13.2
 - python version 3.8
 - image-quality-1.2.7
 - numpy-1.24.2
 -  scikit-image-0.19.3
 - scipy-1.10.0

**Additional context**
Tried with previous versions of scikit image and scipy - same issue, however. Any help in getting this amazing tool to work is appreciated!

**Comment by Nivratti** [comment]
Convert image to RGB before passing to model. Image with alpha channel will give this issue.

```python
img = PIL.Image.open(image_filepath)
img = img.convert("RGB")
quality_score = brisque.score(img)
```

**Comment by srikarad07** [comment]
@Nivratti Thanks for the response! It works, cheers!
